### ISSUE TITLE
Dependancies problems (pycrypto)

### ISSUE THREAD

**Issue by edmont** [libkeepass/libkeepass#11]
Currently the required [pycrypto](https://www.dlitz.net/software/pycrypto/) module seems to be obsolete. In my case, when I try to install **libkeepass** with pip in Python 3.6.3 I get an error:

`Command "c:\users\developer\appdata\local\programs\python\python36-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\DEVELO~1\\AppData\\Local\\Temp\\pip-build-asfco2ez\\pycrypto\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\DEVELO~1\AppData\Local\Temp\pip-go_dwqhk-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\DEVELO~1\AppData\Local\Temp\pip-build-asfco2ez\pycrypto\`

I guess it would not hurt to use the newest pycrypto replacement, [pycryptodome](https://github.com/Legrandin/pycryptodome).

**Comment by Evidlo** [comment]
I agree that moving to `pycryptodome` is probably a good idea.  

I just tried this in Python 3.6.3 on Fedora and the install worked fine

**Comment by Evidlo** [comment]
Also see #12
