### ISSUE TITLE
Switch to pycryptodome

### ISSUE THREAD

**Issue by Evidlo** [libkeepass/libkeepass#12]
It's been years since `pycrypto` was last updated.  We should consider switching to [pycryptodome](https://github.com/Legrandin/pycryptodome)

## Issues
- `pycryptodome` has no `Crypto.Cipher.XOR`, imported by `CryptoPlus.Cipher.__init__`
- CryptoPlus tries to check `Crypto.__version__`, which doesn't exist for `pycryptodome`

One solution is to just drop support for [twofish encryption v1 databases](https://keepass.info/help/base/security.html), which is the only reason were using the `CryptoPlus` library.  We might want to do this anyway, as `CryptoPlus` is just as outdated as `pycrypto` and isn't even available on PyPi.

**Comment by gwerbin** [comment]
How hard would this really be? It looks like all the pycrypto imports are confined to https://github.com/libkeepass/libkeepass/blob/master/libkeepass/crypto.py, and from my reading of the docs at https://www.pycryptodome.org/en/latest/src/vs_pycrypto.html you should just be able to drop in Pycryptodome with no changes.

Edit: I just tried it and all tests pass except the CryptoPlus stuff.
