### ISSUE TITLE
No KDBXv4 Support - possibly incorrect documentation?

### ISSUE THREAD

**Issue by subdavis** [libkeepass/libkeepass#13]
Hey there!

I'm a little confused about the claims in the description and README.

KDBXv4 is clearly documented in https://keepass.info/help/kb/kdbx_4.html to include support for ChaCha20 and Argon2.

There seems to be some confusion between what v4 means.  It isn't any file created by a KeePass2 client - it explicitly implies support for these new algorithms.

Could the developer(s) provide some justification for why libkeepass is advertised in this way? 

Thanks in advance!

**Comment by Evidlo** [comment]
`libkeepass` might be switching to `pycryptodome` soon, which has support for chacha20 already and planned support for argon2.  In the meantime, I'll add a note to the README about lack of support for these algorithms.

**Comment by Evidlo** [comment]
See [libkeepass_proto](http://github.com/libkeepass/libkeepass_proto) for KDBX4 support.
