### ISSUE TITLE
Support for chacha20 (and argon?)

### ISSUE THREAD

**Issue by Evidlo** [libkeepass/libkeepass#17]
As per #13, there is no support for chacha20 (which wasn't available with PyCrypto).  Now that we are using pycryptodome, this should be easy to implement.

We should also keep an eye out for when pycryptodome adds argon2 support.

**Comment by crass** [comment]
Depends how you define easy.  pycryptodome implements the original ChaCha20 specification which uses 64bit nonce, not the 96bit nonce specified in RFC7539 which KeePass uses.  It wouldn't be too hard to change pycryptodome's implementation to use the larger nonce, but I'm not sure if they'd accept the changes yet.  I've created an issue on the pycryptodome project.  Also, I have a branch, [chacha20](https://github.com/crass/libkeepass/tree/chacha20), which should work (removing the last commit) once this issue with pycryptodome is resolved.

**Comment by crass** [comment]
Well that was quick, pycryptodome added [RFC7539 support](https://github.com/Legrandin/pycryptodome/commit/c2df8cc6046c016286f9e4d925dc6c521f4f6a17) in master and it should be in the next release.  I've updated my chacha20 branch such that it successfully decrypts a ChaCha20 encrypted sample keepass file in tests.  Currently it is not supported to decrypt protected passwords encrypted with chacha20 (ie. replacing Salsa20 with ChaCha20).
