### ISSUE TITLE
Protect/Unprotect Passwords

### ISSUE THREAD

**Issue by keans** [libkeepass/libkeepass#20]
I have a question regarding the `protect` function of the `KDBXmlExtension` class: when I call the `protect` function, e.g. on Password 12345, the outcome in XML is `<Value Protected="False" ProtectedValue="e5IVjGY=">12345</Value>`. It seems to me that the password has been successfully be encrypted to the `ProtectedValue`; however, the text field of the value still reveals the original password. 

Is this behavior intended or do I missing something? I thought this function used to protect the passwords when stored in memory?

**Comment by crass** [comment]
If the above xml is obtained after calling the `protect` method, then there is a bug.  The output should look like `<Value Protected="True">e5IVjGY=</Value>` after calling `protect`.  Can you provide a simple kdb4 xml file that looks as you've sid above after calling the `protect` method?

**Comment by keans** [comment]
Hm, sadly I deleted my test data and I cannot reproduce the described behavior. Maybe I just mixed up the order of calls. Sorry, for the noise.
