### ISSUE TITLE
python3: silent error while loading keyfile

### ISSUE THREAD

**Issue by netixx** [libkeepass/libkeepass#28]
When using libkeepass v0.3.0 from pypi with python3 and specifying a keyfile, libkeepass fails to decrypt the file (raising IOError).

The following issues occur:
1. The keyfile load silently fails because of the `except: pass` directives in `common.py/load_keyfile`.
2. When the key is not xml, `load_plain_keyfile` raises an exception when key length is 64 (the code attempts to decode the string as hex)
3. The problem is in function `load_plain_keyfile` because python3 does not support `.decode('hex')` (raises an exeption), replacing this with `codecs.decode(key, 'hex')` solves the problem (on python3)

This would fix the problem with python3 and should work the same with python2 (but I couldn't test this).

Thank you for your work!

**Comment by Evidlo** [comment]
Fixed by https://github.com/libkeepass/libkeepass/commit/dfd47b072966e8c5db6f17b7af3d59b82b3d39c2
