### ISSUE TITLE
missing libkeepass/utils directory in release 0.3.1

### ISSUE THREAD

**Issue by sebns** [libkeepass/libkeepass#32]
From https://pypi.org/project/libkeepass/0.3.1/#files

It looks like `utils.py` in 0.3.0 has changed and is now a directory, but it is missing in 0.3.1 (released 31 july 2019).

I get this error (due to missing directory `./utils/`):
```
ModuleNotFoundError: No module named 'libkeepass.utils'
```

**Comment by Evidlo** [comment]
Should be fixed now.
