### ISSUE TITLE
UnboundLocalError: local variable 'mm_op' referenced before assignment

### ISSUE THREAD

**Issue by SCOTT-HAMILTON** [libkeepass/libkeepass#33]
The variable mm_op in some cases can be referenced before assignement : 
https://github.com/libkeepass/libkeepass/blob/master/libkeepass/utils/merge.py#L312

**Comment by crass** [comment]
It would be helpful to see the sequence of commands used to get to that point. If you're creating a KDB4Merge object, then `__init__` should be run and it initializes `mm_ops` before it can get to that referenced code. So what you're saying shouldn't be possible unless you're messing with the internals of the object yourself.

**Comment by SCOTT-HAMILTON** [comment]
Unfortunately, I can't reproduce it, I'll have to close this.
