### ISSUE TITLE
Two undefined names in tests/__init__.py

### ISSUE THREAD

**Issue by cclauss** [libkeepass/libkeepass#9]
flake8 testing of https://github.com/libkeepass/libkeepass on Python 2.7.13

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./tests/__init__.py:6:41: F821 undefined name 'helloworld'
    suite.addTests(doctest.DocTestSuite(helloworld))
                                        ^

./tests/__init__.py:7:20: F821 undefined name 'test_helloworld'
    suite.addTests(test_helloworld.suite())
                   ^
```

**Comment by Evidlo** [comment]
We should probably just delete everything in `__init__.py`.  I've just been calling `tests.py` directly.
